name: "Jekyll true minimal theme"
description: "Lightweight theme"

url: '' 
baseurl: ''

markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-paginate
paginate: 10
paginate_path: /page-:num

#disqus-id: your-disqus-id

source: .
destination: ./_site

sass:
    style: :compressed
    sass_dir: assets/css/
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
