remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Site settings
  title: Jayson Blog
  SEOTitle: Jayson | My Blog
  header-img: img/post-bg-desk.jpg
  email: zqin14@stevens.edu
  description: "Welcome to my blog"
  keyword: "My Blog"
  url: "http://JaysonQin.github.io"          #ID
  baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
  github_repo: "https://github.com/JaysonQin/JaysonQin.github.io.git" # 用你的ID替换name

  # Sidebar settings
  sidebar: true                           # whether or not using Sidebar.
  sidebar-about-description: "苟利国家生死以，岂因祸福避趋之~"
  sidebar-avatar: /img/avatar_binggan.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`

  # SNS settings
  RSS: false
  github_username:  JaysonQin
